import { Milestone, Domain } from '../../types';

export const adaptiveMilestones: Milestone[] = [
  {
    id: 'ASC_0-3_1',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '0-3',
    description: 'Opens mouth at sight of breast/bottle',
    typicalAge: 2,
    question: 'Baby opens their mouth when they see a breast or bottle coming',
    isRedFlag: () => false,
    canonicalId: 'COG_0-3_3'
  },
  {
    id: 'ASC_4-6_2',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '4-6',
    description: 'Reaches for spoon or bottle during feeding',
    typicalAge: 5,
    question: 'Baby reaches for the spoon or tries to hold the bottle when you feed them',
    // Most infants start reaching for a spoon or bottle around 5 months; concern if not by 9 months
    isRedFlag: (age) => age >= 9,
    dependsOn: ['ASC_0-3_1']
  },
  {
    id: 'ASC_4-6_1',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '4-6',
    description: 'Begins to hold and mouth foods',
    typicalAge: 7,
    question: 'Does your baby hold onto and bring soft finger foods (like a teething cracker) to their mouth?',
    isRedFlag: (age) => age >= 9,
    dependsOn: ['FM_0-3_1', 'ASC_4-6_2']
  },
  {
    id: 'ASC_7-9_4',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '7-9',
    description: 'Offers arm or leg during dressing',
    typicalAge: 9,
    question: 'When you are putting on your baby’s clothes, do they help by pushing an arm or leg through the sleeve or pant leg?',
    // Cooperative dressing often begins around 9 months; concern if absent by 15 months
    isRedFlag: (age) => age >= 15,
  },
  {
    id: 'ASC_7-9_1',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '7-9',
    description: 'Holds bottle independently',
    typicalAge: 8,
    question: 'Can your baby hold their own bottle to drink?',
    isRedFlag: (age) => age >= 12,
    dependsOn: ['ASC_4-6_2']
  },
  {
    id: 'ASC_7-9_2',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '7-9',
    description: 'Feeds self with fingers (pincer grasp emerging)',
    typicalAge: 9,
    question: 'Does your baby pick up small pieces of food with their thumb and fingers to feed themselves?',
    isRedFlag: (age) => age >= 12,
    dependsOn: ['ASC_4-6_1']
  },
  {
    id: 'ASC_7-9_3',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '7-9',
    description: 'Self‑feeds soft finger foods using raking or emerging pincer grasp',
    typicalAge: 9,
    question: 'Does your baby feed themself small pieces of food using their fingers?',
    // Self‑feeding should emerge by the end of the first year【877465663938624†L587-L591】,
    isRedFlag: (age) => age >= 12,
    dependsOn: ['ASC_7-9_2']
  },
  {
    id: 'ASC_10-12_1',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '10-12',
    description: 'Drinks from cup (held by adult)',
    typicalAge: 12,
    question: 'Can your baby drink from a cup that you are holding for them?',
    isRedFlag: () => false,
    dependsOn: ['ASC_7-9_1']
  },
  {
    id: 'ASC_10-12_2',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '10-12',
    description: 'Attempts to use a spoon',
    typicalAge: 12,
    question: 'Does your baby try to use a spoon to feed themselves, even just by dipping and licking?',
    isRedFlag: (age) => age >= 18,
    dependsOn: ['ASC_7-9_3', 'FM_7-9_1']
  },
  {
    id: 'ASC_10-12_3',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '10-12',
    description: 'Cooperates with dressing by holding arms and legs out',
    typicalAge: 12,
    question: 'Does your baby help when getting dressed by holding out their arms or legs?',
    isRedFlag: (age) => age >= 18,
    dependsOn: ['ASC_7-9_4']
  },
  {
    id: 'ASC_10-12_4',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '10-12',
    description: 'Helps tidy up by handing objects or dropping them into a container',
    typicalAge: 12,
    question: 'When it’s time to clean up, will your baby hand you toys or drop them into a box?',
    isRedFlag: (age) => age >= 18,
    dependsOn: ['COG_10-12_2'],
  },
  {
    id: 'ASC_13-18_2',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '13-18',
    description: 'Feeds self with fingers and drinks from a cup with two hands',
    typicalAge: 15,
    question: 'Can your child feed themselves using their fingers and drink from a cup they hold with both hands, even if they spill?',
    isRedFlag: (age) => age >= 20,
    dependsOn: ['ASC_10-12_1', 'ASC_7-9_2']
  },
  {
    id: 'ASC_13-18_1',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '13-18',
    description: 'Eats with a spoon (moderate spilling)',
    typicalAge: 18,
    question: 'Can your child successfully scoop food with a spoon and bring it to their mouth, even if they spill?',
    isRedFlag: (age) => age >= 24,
    dependsOn: ['ASC_10-12_2'],
  },
  {
    id: 'ASC_13-18_3',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '13-18',
    description: 'Helps wash hands and face',
    typicalAge: 18,
    question: 'Does your child enjoy helping wash their hands and face at the sink?',
    isRedFlag: (age) => age >= 24,
    dependsOn: ['COG_10-12_5'],
  },
  {
    id: 'ASC_19-24_2',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '19-24',
    description: 'Removes an article of clothing',
    typicalAge: 24,
    question: 'Can your child take off an item of clothing, like socks or a hat?',
    isRedFlag: (age) => age >= 30,
    dependsOn: ['ASC_10-12_3'],
  },
  {
    id: 'ASC_19-24_1',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '19-24',
    description: 'Eats with a spoon well',
    typicalAge: 24,
    question: 'Can your child eat with a spoon with little spilling?',
    isRedFlag: (age) => age > 30,
    dependsOn: ['ASC_13-18_1']
  },
  {
    id: 'ASC_19-24_3',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '19-24',
    description: 'Removes simple clothing like hat or shoes',
    // Toddlers often begin undressing themselves between 18–24 months【877465663938624†L610-L617】,
    typicalAge: 24,
    question: 'Can your child take off simple clothing items like their hat, socks or shoes?',
    isRedFlag: (age) => age >= 30,
    dependsOn: ['ASC_19-24_2']
  },
  {
    id: 'ASC_19-24_4',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '19-24',
    description: 'Shows signs of toilet readiness (remains dry 2 hours, indicates need to go)',
    // Signs of toilet readiness and interest often emerge around the second year【877465663938624†L587-L591】,
    typicalAge: 24,
    question: 'Does your child stay dry for at least two hours and let you know when they need a diaper change or want to use the potty?',
    isRedFlag: (age) => age >= 36,
  },
  {
    id: 'ASC_25-36_4',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '25-36',
    description: 'Uses a fork and drinks from an open cup without spilling',
    typicalAge: 30,
    question: 'Does your child use a fork to eat and drink from an open cup with little spilling?',
    isRedFlag: (age) => age > 36,
    dependsOn: ['ASC_19-24_1', 'ASC_13-18_2']
  },
  {
    id: 'ASC_25-36_1',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '25-36',
    description: 'Dresses self (undresses completely)',
    typicalAge: 36,
    question: 'Can your child undress themself completely?',
    isRedFlag: (age) => age > 42,
    dependsOn: ['ASC_19-24_3']
  },
  {
    id: 'ASC_25-36_3',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '25-36',
    description: 'Puts on T‑shirt with minimal assistance',
    // By age 3 many children can put on a T‑shirt【877465663938624†L659-L668】,
    typicalAge: 36,
    question: 'Can your child put on a T‑shirt by themselves, needing only a little help?',
    isRedFlag: (age) => age > 42,
    dependsOn: ['ASC_25-36_1']
  },
  {
    id: 'ASC_25-36_6',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '25-36',
    description: 'Washes and dries hands independently',
    typicalAge: 36,
    question: 'Can your child wash and dry their hands on their own, perhaps needing a stool to reach the sink?',
    isRedFlag: (age) => age > 42,
    dependsOn: ['ASC_13-18_3'],
  },
  {
    id: 'ASC_25-36_5',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '25-36',
    description: 'Brushes teeth with assistance',
    typicalAge: 36,
    question: 'Does your child attempt to brush their teeth when given a toothbrush, with you helping to finish?',
    isRedFlag: (age) => age > 42,
    dependsOn: ['ASC_25-36_6']
  },
  {
    id: 'ASC_25-36_2',
    domain: Domain.ADAPTIVE_SELF_CARE,
    ageGroup: '25-36',
    description: 'Toilet trained',
    typicalAge: 36,
    question: 'Is your child mostly toilet trained during the day?',
    isRedFlag: (age) => age > 42,
    dependsOn: ['ASC_19-24_4']
  },
];