import { Milestone, Domain } from '../../types';

/*
 * Cognitive milestones capture how a child thinks, learns and solves problems.
 * The milestones below are based on evidence from reputable health sources such
 * as the Cleveland Clinic’s developmental milestone lists and the Children’s
 * Hospital of Philadelphia (CHOP) developmental guidelines. For example,
 * Cleveland Clinic notes that by around 6 months babies put objects in their
 * mouths to learn about them and reach for toys they want【978140674183011†L170-L183】.
 * By 9 months, most babies look for things they drop and bang objects
 * together【978140674183011†L190-L199】, showing early problem‑solving and
 * cause‑and‑effect learning. At 12 months they place smaller things into
 * larger containers and search for hidden objects【978140674183011†L216-L219】.
 * CHOP’s 2‑ and 3‑year milestones include sorting shapes and colors,
 * completing simple puzzles, counting to three and engaging in make‑believe
 * play【877465663938624†L659-L668】. These milestones have been
 * incorporated below with typical ages and conservative red‑flag ages.
 */

export const cognitiveMilestones: Milestone[] = [
  // 0–3 months: early cognitive engagement and sensory responses
  {
    id: 'COG_0-3_1',
    domain: Domain.COGNITIVE,
    ageGroup: '0-3',
    description: 'Pays attention to faces and follows moving objects with eyes',
    typicalAge: 2,
    question: 'Baby looks at your face and tracks a moving toy or object with their eyes',
    isRedFlag: (age) => age >= 4,
  },
  {
    id: 'COG_0-3_2',
    domain: Domain.COGNITIVE,
    ageGroup: '0-3',
    description: 'Turns toward familiar voices or sounds',
    typicalAge: 2,
    question: 'Baby turns their head or eyes toward the noise when you speak or make a sound',
    isRedFlag: (age) => age >= 4,
  },
  {
    id: 'COG_0-3_3',
    domain: Domain.COGNITIVE,
    ageGroup: '0-3',
    description: 'Shows anticipation of feeding by opening mouth when seeing bottle or breast',
    typicalAge: 3,
    question: 'Baby opens their mouth or shows excitement when they see a breast or bottle coming',
    isRedFlag: (age) => age >= 5,
    dependsOn: ['COG_0-3_1']
  },
  {
    id: 'COG_0-3_4',
    domain: Domain.COGNITIVE,
    ageGroup: '0-3',
    description: 'Explores hands and brings them to mouth',
    typicalAge: 3,
    question: 'Baby looks at their hands and brings them to their mouth to explore',
    isRedFlag: (age) => age >= 5,
  },

  // 4–6 months: increasing curiosity and basic problem‑solving
  {
    id: 'COG_4-6_1',
    domain: Domain.COGNITIVE,
    ageGroup: '4-6',
    description: 'Reaches for toys and tries to grasp objects of interest',
    // Babies reach for toys they want around 6 months【978140674183011†L175-L180】
    typicalAge: 6,
    question: 'Baby reaches out for toys or objects they want to explore',
    isRedFlag: (age) => age >= 8,
    dependsOn: ['COG_0-3_1'],
  },
  {
    id: 'COG_4-6_2',
    domain: Domain.COGNITIVE,
    ageGroup: '4-6',
    description: 'Explores objects by putting them in their mouth',
    // Putting objects in the mouth is common by 6 months【978140674183011†L175-L180】
    typicalAge: 6,
    question: 'Baby explores new objects by bringing them to their mouth',
    isRedFlag: (age) => age >= 9,
    dependsOn: ['COG_4-6_1', 'COG_0-3_4'],
  },
  {
    id: 'COG_4-6_3',
    domain: Domain.COGNITIVE,
    ageGroup: '4-6',
    description: 'Recognizes familiar people and smiles at own reflection',
    // By 6 months babies recognize familiar people and enjoy seeing themselves in mirrors【978140674183011†L186-L188】
    typicalAge: 6,
    question: 'Baby recognizes familiar people and smiles at themselves in a mirror',
    isRedFlag: (age) => age >= 9,
    dependsOn: ['COG_0-3_1'],
  },
  {
    id: 'COG_4-6_4',
    domain: Domain.COGNITIVE,
    ageGroup: '4-6',
    description: 'Responds to own name consistently',
    typicalAge: 6,
    question: 'Baby turns toward you or makes eye contact when you call their name',
    isRedFlag: (age) => age >= 9,
    dependsOn: ['COG_0-3_2'],
  },
  {
    id: 'COG_4-6_5',
    domain: Domain.COGNITIVE,
    ageGroup: '4-6',
    description: 'Shakes or bangs toys to make noise (cause‑and‑effect play)',
    // Playing by banging objects together develops around 6–9 months【978140674183011†L190-L199】
    typicalAge: 6,
    question: 'Baby shakes or bangs toys to hear the sounds they make',
    isRedFlag: (age) => age >= 9,
    dependsOn: ['COG_4-6_1'],
  },

  // 7–9 months: object permanence and intentional problem solving
  {
    id: 'COG_7-9_1',
    domain: Domain.COGNITIVE,
    ageGroup: '7-9',
    description: 'Looks for objects they drop or partially hidden objects',
    // By 9 months babies look for things they drop【978140674183011†L190-L199】
    typicalAge: 8,
    question: 'Baby looks around or reaches for a toy when it falls out of sight',
    isRedFlag: (age) => age >= 12,
    dependsOn: ['COG_4-6_1'],
  },
  {
    id: 'COG_7-9_2',
    domain: Domain.COGNITIVE,
    ageGroup: '7-9',
    description: 'Plays peek‑a‑boo and enjoys interactive games',
    typicalAge: 9,
    question: 'Baby smiles or laughs when you play peek‑a‑boo or similar hiding games',
    isRedFlag: (age) => age >= 12,
    dependsOn: ['COG_7-9_1'],
    canonicalId: 'SE_7-9_3'
  },
  {
    id: 'COG_7-9_3',
    domain: Domain.COGNITIVE,
    ageGroup: '7-9',
    description: 'Transfers objects from one hand to the other and bangs them together',
    typicalAge: 8,
    question: 'Baby switches a toy from one hand to the other and bangs two toys together',
    isRedFlag: (age) => age >= 12,
    dependsOn: ['COG_4-6_5'],
  },
  {
    id: 'COG_7-9_4',
    domain: Domain.COGNITIVE,
    ageGroup: '7-9',
    description: 'Understands the word “no” and pauses briefly when you say it',
    typicalAge: 9,
    question: 'Baby stops and looks at you when you firmly say "no"',
    isRedFlag: (age) => age >= 12,
    dependsOn: ['COG_4-6_4'],
  },
  {
    id: 'COG_7-9_5',
    domain: Domain.COGNITIVE,
    ageGroup: '7-9',
    description: 'Looks for an object after watching you hide it (emerging object permanence)',
    typicalAge: 9,
    question: 'Baby lifts the blanket to find a toy when you hide it under a blanket while they watch',
    isRedFlag: (age) => age >= 12,
    dependsOn: ['COG_7-9_1'],
  },
  {
    id: 'COG_7-9_6',
    domain: Domain.COGNITIVE,
    ageGroup: '7-9',
    description: 'Uses gestures like pointing to indicate interest or to share things with you',
    typicalAge: 9,
    question: 'Baby points at something interesting or raises their arms to show they want to be picked up',
    isRedFlag: (age) => age >= 12,
    dependsOn: ['COG_4-6_1'],
  },

  // 10–12 months: purposeful play and problem solving
  {
    id: 'COG_10-12_1',
    domain: Domain.COGNITIVE,
    ageGroup: '10-12',
    description: 'Finds hidden objects easily and enjoys searching games',
    // At 12 months babies look for objects you hide【978140674183011†L216-L219】
    typicalAge: 11,
    question: 'Baby quickly finds their toy when you hide it behind your back or under a cup',
    isRedFlag: (age) => age >= 15,
    dependsOn: ['COG_7-9_5'],
  },
  {
    id: 'COG_10-12_2',
    domain: Domain.COGNITIVE,
    ageGroup: '10-12',
    description: 'Places smaller objects into larger containers and dumps them out',
    // Placing objects into containers emerges around 12 months【978140674183011†L216-L219】
    typicalAge: 12,
    question: 'Baby puts small items into a box or container and then dumps them back out',
    isRedFlag: (age) => age >= 18,
    dependsOn: ['COG_7-9_3'],
  },
  {
    id: 'COG_10-12_3',
    domain: Domain.COGNITIVE,
    ageGroup: '10-12',
    description: 'Looks at the correct picture when an object is named',
    typicalAge: 12,
    question: 'If you ask “Where is the ball?” does your baby look toward the picture of a ball or the actual ball?',
    isRedFlag: (age) => age >= 18,
    dependsOn: ['COG_4-6_4'],
  },
  {
    id: 'COG_10-12_4',
    domain: Domain.COGNITIVE,
    ageGroup: '10-12',
    description: 'Begins to use objects correctly (e.g., drinks from cup, brushes hair)',
    typicalAge: 12,
    question: 'Does your baby try to use common objects correctly, like pretending to drink from a cup or brush their hair?',
    isRedFlag: (age) => age >= 18,
    dependsOn: ['COG_7-9_3'],
  },
  {
    id: 'COG_10-12_5',
    domain: Domain.COGNITIVE,
    ageGroup: '10-12',
    description: 'Follows simple directions, such as “pick up the toy”',
    typicalAge: 12,
    question: 'If you give a simple instruction like “pick up the toy” or “come here,” does your baby respond?',
    isRedFlag: (age) => age >= 18,
    dependsOn: ['COG_7-9_4'],
  },
  {
    id: 'COG_10-12_6',
    domain: Domain.COGNITIVE,
    ageGroup: '10-12',
    description: 'Imitates simple gestures or actions (e.g., clapping, waving)',
    typicalAge: 12,
    question: 'When you wave, clap or blow a kiss, does your baby imitate the action?',
    isRedFlag: (age) => age >= 18,
    dependsOn: ['COG_4-6_3'],
  },

  // 13–18 months: early problem solving and pretend play
  {
    id: 'COG_13-18_1',
    domain: Domain.COGNITIVE,
    ageGroup: '13-18',
    description: 'Points to body parts when asked (e.g., nose, eyes, tummy)',
    // By 18 months many toddlers point to body parts when named【694903796263326†L93-L116】
    typicalAge: 16,
    question: 'If you ask “Where’s your nose?” or “Where’s your tummy?” does your child point to it?',
    isRedFlag: (age) => age >= 24,
    dependsOn: ['COG_10-12_3'],
  },
  {
    id: 'COG_13-18_2',
    domain: Domain.COGNITIVE,
    ageGroup: '13-18',
    description: 'Scribbles spontaneously on paper or surfaces',
    // Spontaneous scribbling develops around 16–18 months【694903796263326†L93-L116】
    typicalAge: 16,
    question: 'Does your child make marks or scribbles on paper with a crayon or marker without being shown?',
    isRedFlag: (age) => age >= 24,
    dependsOn: ['FM_7-9_1']
  },
  {
    id: 'COG_13-18_3',
    domain: Domain.COGNITIVE,
    ageGroup: '13-18',
    description: 'Engages in simple pretend play (feeding doll, brushing teddy bear’s hair)',
    // Pretend play with dolls and animals typically begins by 18 months【694903796263326†L93-L116】
    typicalAge: 18,
    question: 'Does your child pretend to feed a doll or brush a stuffed animal’s hair?',
    isRedFlag: (age) => age >= 24,
    dependsOn: ['COG_10-12_4']
  },
  {
    id: 'COG_13-18_4',
    domain: Domain.COGNITIVE,
    ageGroup: '13-18',
    description: 'Understands and follows one‑step directions (e.g., “give it to me”)',
    typicalAge: 16,
    question: 'If you give a simple instruction like “give me the ball,” does your child respond appropriately?',
    isRedFlag: (age) => age >= 24,
    dependsOn: ['COG_10-12_5'],
  },
  {
    id: 'COG_13-18_5',
    domain: Domain.COGNITIVE,
    ageGroup: '13-18',
    description: 'Begins sorting objects by shape or color with help',
    typicalAge: 18,
    question: 'Does your child try to match shapes or colors, such as fitting shapes into a sorter or grouping colored blocks?',
    isRedFlag: (age) => age >= 24,
    dependsOn: ['COG_10-12_2'],
  },
  {
    id: 'COG_13-18_6',
    domain: Domain.COGNITIVE,
    ageGroup: '13-18',
    description: 'Recognizes self in mirror and points to own reflection',
    typicalAge: 18,
    question: 'When looking in a mirror, does your child seem to recognize themselves (e.g., pointing to their own nose or hair)?',
    isRedFlag: (age) => age >= 24,
    dependsOn: ['COG_4-6_3'],
  },
  {
    id: 'COG_13-18_7',
    domain: Domain.COGNITIVE,
    ageGroup: '13-18',
    description: 'Solves simple problems through trial and error (e.g., figuring out how to open a box)',
    typicalAge: 18,
    question: 'Does your child experiment with ways to open a box or reach a toy that is out of reach?',
    isRedFlag: (age) => age >= 30,
    dependsOn: ['COG_10-12_1'],
  },

  // 19–24 months: symbolic thought and more complex play
  {
    id: 'COG_19-24_1',
    domain: Domain.COGNITIVE,
    ageGroup: '19-24',
    description: 'Completes a simple shape‑sorting puzzle or inset puzzle (3–4 pieces)',
    // CHOP lists completing simple puzzles by around 2 years【877465663938624†L610-L617】
    typicalAge: 22,
    question: 'Can your child place shapes into the correct holes or complete a small puzzle of a few pieces?',
    isRedFlag: (age) => age >= 30,
    dependsOn: ['COG_13-18_5'],
  },
  {
    id: 'COG_19-24_2',
    domain: Domain.COGNITIVE,
    ageGroup: '19-24',
    description: 'Sorts objects by shape and color more consistently',
    // Sorting shapes and colors is a 2‑year milestone【877465663938624†L587-L591】
    typicalAge: 24,
    question: 'Does your child sort blocks or objects by shape or color without being told?',
    isRedFlag: (age) => age >= 30,
    dependsOn: ['COG_13-18_5'],
  },
  {
    id: 'COG_19-24_3',
    domain: Domain.COGNITIVE,
    ageGroup: '19-24',
    description: 'Matches pictures and objects (e.g., matching a toy dog to a picture of a dog)',
    // Matching pictures and objects is a skill described by CHOP for toddlers【877465663938624†L610-L617】
    typicalAge: 24,
    question: 'If you show a picture of an animal and have toy animals, does your child match the toy to the picture?',
    isRedFlag: (age) => age >= 30,
    dependsOn: ['COG_10-12_3'],
  },
  {
    id: 'COG_19-24_4',
    domain: Domain.COGNITIVE,
    ageGroup: '19-24',
    description: 'Groups similar objects together (e.g., all cars, all animals)',
    typicalAge: 24,
    question: 'Does your child group similar toys (like cars together and animals together) without prompting?',
    isRedFlag: (age) => age >= 30,
    dependsOn: ['COG_13-18_5'],
  },
  {
    id: 'COG_19-24_5',
    domain: Domain.COGNITIVE,
    ageGroup: '19-24',
    description: 'Understands simple concepts like “in” and “on” or “big” and “little”',
    typicalAge: 24,
    question: 'If you ask your child to put a toy “in the box” or “on the table,” do they follow correctly? Do they understand big and little?',
    isRedFlag: (age) => age >= 30,
    dependsOn: ['COG_13-18_4'],
  },
  {
    id: 'COG_19-24_6',
    domain: Domain.COGNITIVE,
    ageGroup: '19-24',
    description: 'Imitates daily routines and uses objects symbolically (e.g., sweeping with a toy broom)',
    typicalAge: 24,
    question: 'Does your child copy everyday activities, like pretending to sweep or cook?',
    isRedFlag: (age) => age >= 30,
    dependsOn: ['COG_13-18_3'],
  },
  {
    id: 'COG_19-24_7',
    domain: Domain.COGNITIVE,
    ageGroup: '19-24',
    description: 'Shows interest in picture books and points to named objects',
    typicalAge: 22,
    question: 'When you look at a picture book together, does your child point to pictures when you name them?',
    isRedFlag: (age) => age >= 30,
    dependsOn: ['COG_10-12_3'],
  },
  {
    id: 'COG_19-24_8',
    domain: Domain.COGNITIVE,
    ageGroup: '19-24',
    description: 'Begins to recognize and say some shapes (e.g., circle, square)',
    typicalAge: 24,
    question: 'Can your child identify simple shapes like a circle or square, either by saying the word or pointing?',
    isRedFlag: (age) => age >= 30,
    dependsOn: ['COG_19-24_1'],
  },

  // 25–36 months: advanced cognitive abilities and symbolic play
  {
    id: 'COG_25-36_1',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Sorts objects by shape, color and size without assistance',
    // Sorting by shape and color is expected by 2½–3 years【877465663938624†L659-L668】
    typicalAge: 30,
    question: 'Does your child independently sort toys by shape, color or size, such as grouping all the blue blocks together?',
    isRedFlag: (age) => age > 36,
    dependsOn: ['COG_19-24_2'],
  },
  {
    id: 'COG_25-36_2',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Completes puzzles with four to six pieces',
    typicalAge: 30,
    question: 'Can your child finish a jigsaw puzzle of about four to six interlocking pieces?',
    isRedFlag: (age) => age > 36,
    dependsOn: ['COG_19-24_1'],
  },
  {
    id: 'COG_25-36_3',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Counts to three and understands the concept of “two”',
    // Counting three objects and understanding “two” are 3‑year milestones【877465663938624†L659-L668】
    typicalAge: 34,
    question: 'Does your child count to three or demonstrate understanding of quantities like “one” and “two”?',
    isRedFlag: (age) => age > 42,
    dependsOn: ['LANG_19-24_1'],
  },
  {
    id: 'COG_25-36_4',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Names several colors and begins to recognize numerals or letters',
    typicalAge: 34,
    question: 'Can your child name some colors and recognize a few numbers or letters when shown?',
    isRedFlag: (age) => age > 42,
    dependsOn: ['COG_25-36_3'],
  },
  {
    id: 'COG_25-36_5',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Engages in imaginative play with multiple roles (e.g., pretending to cook, drive or doctor)',
    typicalAge: 30,
    question: 'Does your child create imaginative scenarios, like pretending to cook dinner or drive a car with dolls or stuffed animals as participants?',
    isRedFlag: (age) => age > 36,
    dependsOn: ['COG_19-24_6'],
  },
  {
    id: 'COG_25-36_6',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Understands size comparisons (big/little, short/tall) and uses them correctly',
    typicalAge: 34,
    question: 'Does your child correctly identify objects as big or little, tall or short when asked?',
    isRedFlag: (age) => age > 42,
    dependsOn: ['COG_19-24_5'],
  },
  {
    id: 'COG_25-36_7',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Solves simple problems independently (e.g., dragging a stool to reach something)',
    typicalAge: 32,
    question: 'If your child wants something out of reach, do they figure out how to get it, such as moving a chair or stool?',
    isRedFlag: (age) => age > 40,
    dependsOn: ['COG_13-18_7'],
  },
  {
    id: 'COG_25-36_8',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Understands sequences and follows three‑step directions',
    typicalAge: 34,
    question: 'Can your child follow a three‑step instruction like “Pick up your toy, put it in the box and come back to me”?',
    isRedFlag: (age) => age > 42,
    dependsOn: ['COG_19-24_5', 'LANG_19-24_4'],
  },
  {
    id: 'COG_25-36_9',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Understands concept of pretend vs real (e.g., knows a toy is not alive)',
    typicalAge: 36,
    question: 'Does your child understand that pretend play with toys is not real, like knowing a toy bear is not a real bear?',
    isRedFlag: (age) => age > 48,
    dependsOn: ['COG_25-36_5'],
  },
  {
    id: 'COG_25-36_10',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Knows own first and last name, age and sex',
    // Knowing own name/age/sex is a 3‑year milestone【531272518406281†L96-L122】
    typicalAge: 36,
    question: 'If asked, can your child tell you their own first and last name, whether they are a boy or girl, and how old they are?',
    isRedFlag: (age) => age > 48,
    dependsOn: ['LANG_25-36_1'],
  },
  {
    id: 'COG_25-36_11',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Understands time concepts like “now,” “later,” or “soon” in a basic sense',
    typicalAge: 36,
    question: 'When you say you will do something “later” or “soon,” does your child seem to grasp that it will happen in the future?',
    isRedFlag: (age) => age > 48,
    dependsOn: ['COG_25-36_8'],
  },
  {
    id: 'COG_25-36_12',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Understands and uses pronouns correctly (I, you, me, mine)',
    typicalAge: 30,
    question: 'Does your child use pronouns like “I,” “you,” “me” or “mine” appropriately when talking?',
    isRedFlag: (age) => age > 36,
    dependsOn: ['LANG_19-24_2'],
  },
  {
    id: 'COG_25-36_13',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Asks “what,” “where” or “why” questions and shows curiosity about how things work',
    typicalAge: 36,
    question: 'Does your child ask questions such as “What’s that?” “Where did it go?” or “Why?” to learn about the world?',
    isRedFlag: (age) => age > 48,
    dependsOn: ['LANG_19-24_2'],
  },
  {
    id: 'COG_25-36_14',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Recognizes and names several basic shapes (circle, square, triangle)',
    typicalAge: 36,
    question: 'Can your child correctly identify and name simple shapes like a circle, square and triangle?',
    isRedFlag: (age) => age > 48,
    dependsOn: ['COG_19-24_8'],
  },
  {
    id: 'COG_25-36_15',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Knows the difference between “same” and “different” when comparing objects',
    typicalAge: 36,
    question: 'If you show two objects, does your child tell you whether they are the same or different?',
    isRedFlag: (age) => age > 48,
    dependsOn: ['COG_25-36_1'],
  },
  {
    id: 'COG_25-36_16',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Remembers and tells parts of a favorite story or song',
    typicalAge: 36,
    question: 'Can your child recall and repeat parts of a story or sing verses of a favorite song from memory?',
    isRedFlag: (age) => age > 48,
    dependsOn: ['LANG_25-36_1'],
  },
  {
    id: 'COG_25-36_17',
    domain: Domain.COGNITIVE,
    ageGroup: '25-36',
    description: 'Understands simple opposites (hot/cold, up/down)',
    typicalAge: 36,
    question: 'If you ask about opposites like “hot and cold” or “up and down,” does your child understand what they mean?',
    isRedFlag: (age) => age > 48,
    dependsOn: ['COG_25-36_6'],
  },
];