import { Milestone, Domain } from '../../types';

export const languageMilestones: Milestone[] = [
  {
    id: 'LANG_0-3_1',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '0-3',
    description: 'Cooing',
    typicalAge: 2,
    question: 'Baby makes cooing or gurgling sounds',
    isRedFlag: (age) => age >= 4,
  },
  {
    id: 'LANG_4-6_1',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '4-6',
    description: 'Babbles',
    typicalAge: 6,
    question: 'Baby makes babbling sounds with consonants (e.g., "bababa")',
    isRedFlag: (age) => age >= 7,
    dependsOn: ['LANG_0-3_1']
  },
  {
    id: 'LANG_7-9_1',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '7-9',
    description: 'Says "mama/dada" (non-specific)',
    typicalAge: 9,
    question: 'Baby says "mama" or "dada" even if not referring to a specific parent',
    isRedFlag: (age) => age >= 12,
    dependsOn: ['LANG_4-6_1']
  },
  {
    id: 'LANG_10-12_1',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '10-12',
    description: 'One word other than "mama"/"dada"',
    typicalAge: 12,
    question: 'Baby says at least one word other than "mama" or "dada"',
    isRedFlag: (age) => age > 12,
    dependsOn: ['LANG_7-9_1']
  },
  {
    id: 'LANG_13-18_1',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '13-18',
    description: 'Uses at least 6 words',
    typicalAge: 18,
    question: 'Child says at least six words consistently',
    isRedFlag: (age) => age > 18,
    dependsOn: ['LANG_10-12_1']
  },
  {
    id: 'LANG_19-24_1',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '19-24',
    description: '>50-word vocabulary',
    typicalAge: 24,
    question: 'Child has a vocabulary of more than 50 words',
    isRedFlag: (age) => age > 24,
    dependsOn: ['LANG_13-18_1']
  },
  {
    id: 'LANG_19-24_2',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '19-24',
    description: 'Speaks in 2-word combinations',
    typicalAge: 24,
    question: 'Child puts two words together, like "more milk" or "go car"',
    isRedFlag: (age) => age > 24,
    dependsOn: ['LANG_19-24_1', 'LANG_13-18_4']
  },
  {
    id: 'LANG_25-36_1',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '25-36',
    description: 'Speaks in 3-word sentences',
    typicalAge: 36,
    question: 'Child speaks in sentences with three or more words',
    isRedFlag: (age) => age > 36,
    dependsOn: ['LANG_19-24_2']
  },
   {
    id: 'LANG_25-36_2',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '25-36',
    description: '75% of language intelligible to stranger',
    typicalAge: 36,
    question: 'Child speaks clearly enough that a stranger understands about 75% of what they say',
    isRedFlag: (age) => age > 48,
    dependsOn: ['LANG_25-36_1']
  },
  // Additional language milestones for enhanced coverage and precision up to 36 months
  {
    id: 'LANG_0-3_2',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '0-3',
    description: 'Startles or calms in response to sounds or voices',
    typicalAge: 2,
    question: 'Baby startles at loud noises or calms down when you speak or sing to them',
    isRedFlag: (age) => age >= 4,
  },
  {
    id: 'LANG_0-3_3',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '0-3',
    description: 'Uses different cries to express needs (hungry, tired, uncomfortable)',
    typicalAge: 3,
    question: 'Baby has different cries for hunger, tiredness or discomfort',
    isRedFlag: (age) => age >= 6,
  },
  {
    id: 'LANG_4-6_2',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '4-6',
    description: 'Laughs and squeals to express excitement',
    typicalAge: 5,
    question: 'Baby laughs out loud or squeals when something is funny or exciting',
    isRedFlag: (age) => age >= 8,
    dependsOn: ['LANG_0-3_2'],
    canonicalId: 'SE_4-6_2',
  },
  {
    id: 'LANG_4-6_3',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '4-6',
    description: 'Imitates sounds and begins babbling with different pitches',
    typicalAge: 6,
    question: 'Baby imitates sounds you make and babbles with a variety of pitches and syllables',
    isRedFlag: (age) => age >= 8,
    dependsOn: ['LANG_4-6_1']
  },
  {
    id: 'LANG_7-9_2',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '7-9',
    description: 'Responds to own name consistently',
    typicalAge: 9,
    question: 'Baby turns or looks at you when you call their name',
    // Babies usually react to their name by around 9 months【32476239479808†L185-L199】,
    isRedFlag: (age) => age >= 12,
    dependsOn: ['LANG_4-6_3'],
    canonicalId: 'COG_4-6_4',
  },
  {
    id: 'LANG_7-9_3',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '7-9',
    description: 'Uses gestures such as waving or raising arms to communicate',
    typicalAge: 9,
    question: 'Baby uses simple gestures like waving bye‑bye or raising their arms to be picked up',
    isRedFlag: (age) => age >= 12,
  },
  {
    id: 'LANG_10-12_2',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '10-12',
    description: 'Responds to simple verbal requests (e.g., “come here” or “no”)',
    typicalAge: 12,
    question: 'Baby responds appropriately when you say "come here" or "no"',
    isRedFlag: (age) => age >= 18,
    dependsOn: ['LANG_7-9_2']
  },
  {
    id: 'LANG_10-12_3',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '10-12',
    description: 'Uses gestures or words to indicate wants (e.g., pointing and saying “more”)',
    typicalAge: 12,
    question: 'Baby points or uses a word like "more" to tell you what they want',
    isRedFlag: (age) => age >= 18,
    dependsOn: ['LANG_7-9_3']
  },
  {
    id: 'LANG_10-12_4',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '10-12',
    description: 'Imitates simple words, animal sounds or exclamations (e.g., “uh‑oh”)',
    typicalAge: 12,
    question: 'Baby imitates sounds like "woof" for a dog or says "uh‑oh" when something drops',
    isRedFlag: (age) => age >= 18,
    dependsOn: ['LANG_10-12_1']
  },
  {
    id: 'LANG_13-18_2',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '13-18',
    description: 'Uses a vocabulary of about 10–20 words',
    typicalAge: 16,
    question: 'Child says at least 10 different words routinely',
    // By 18 months many children use about 10 words【694903796263326†L93-L116】,
    isRedFlag: (age) => age >= 24,
    dependsOn: ['LANG_10-12_1']
  },
  {
    id: 'LANG_13-18_3',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '13-18',
    description: 'Points to several body parts when named',
    typicalAge: 18,
    question: 'Child points to correct body parts when named',
    isRedFlag: (age) => age >= 24,
    dependsOn: ['LANG_13-18_2'],
    canonicalId: 'COG_13-18_1',
  },
  {
    id: 'LANG_13-18_4',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '13-18',
    description: 'Puts two words together to make simple phrases',
    typicalAge: 18,
    question: 'Child combines two words on their own, such as "all gone" or "more juice"',
    isRedFlag: (age) => age >= 24,
    dependsOn: ['LANG_13-18_2']
  },
  {
    id: 'LANG_19-24_3',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '19-24',
    description: 'Uses pronouns and names pictures (e.g., “I,” “me,” or names three pictures)',
    typicalAge: 24,
    question: 'Child uses words like "I" or "me" and names pictures in a book',
    isRedFlag: (age) => age >= 30,
    dependsOn: ['LANG_19-24_1']
  },
  {
    id: 'LANG_19-24_4',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '19-24',
    description: 'Follows two‑step directions',
    typicalAge: 24,
    question: 'Child follows two‑step instructions such as "Get your shoes and put them by the door"',
    isRedFlag: (age) => age >= 30,
    dependsOn: ['LANG_19-24_2']
  },
  {
    id: 'LANG_25-36_3',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '25-36',
    description: 'Speaks in three‑ to four‑word sentences',
    typicalAge: 30,
    question: 'Child regularly uses sentences of three or more words, like "I want more juice"',
    isRedFlag: (age) => age > 36,
    dependsOn: ['LANG_19-24_2']
  },
  {
    id: 'LANG_25-36_4',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '25-36',
    description: 'Uses simple plurals and prepositions (e.g., “cats,” “in,” “on,” “under”)',
    typicalAge: 36,
    question: 'Child uses plurals and words like "in," "on," or "under" correctly',
    isRedFlag: (age) => age > 42,
    dependsOn: ['LANG_25-36_3']
  },
  {
    id: 'LANG_25-36_5',
    domain: Domain.LANGUAGE_COMMUNICATION,
    ageGroup: '25-36',
    description: 'Counts to three and names at least one color',
    typicalAge: 36,
    question: 'Child counts three objects and names a color such as red or blue',
    isRedFlag: (age) => age > 42,
    dependsOn: ['LANG_25-36_3']
  },
];